mailserver: Improve classifiers / option to file SPAM after user scripts

diff --git a/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/learn b/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/learn
--- a/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/learn
+++ b/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/learn
@@ -1,10 +1,25 @@
 #!/bin/bash
 
 export PATH=/usr/sbin:/usr/bin:/sbin:/bin
-logger -p user.info -t bogofilter "Marking message as {{ item }}."
-output=$(bogofilter -e {% if item == "ham" %}-Sn{% else %}-Ns{% endif %} -M -C 2>&1)
+tmp=`mktemp`
+trap "rm -f $tmp" EXIT
+ret=0
+cat > "$tmp" || ret=$?
+if [ "$ret" != "0" ] ; then
+    logger -p user.error -t bogofilter "Error buffering message to mark as {{ item }}: exited with status $ret"
+    exit "$ret"
+fi
+
+mid=$(grep ^Message-ID: < "$tmp" | head -1 | cut -d '<' -f 2 | cut -d '>' -f 1)
+if [ "$mid" == "" ] ; then mid="with no discernible ID" ; fi
+logger --id=$$ -p user.info -t bogofilter "Marking message $mid as {{ item }}."
+
+tmp2=`mktemp`
+trap "rm -f $tmp $tmp2" EXIT
+bogofilter -e {% if item == "ham" %}-Sn{% else %}-Ns{% endif %} -M -C -I "$tmp" 2> "$tmp2"
 ret=$?
 if [ "$ret" != "0" ] ; then
-    logger -p user.error -t bogofilter "Error marking message as {{ item }}: $output"
+    output=`cat "$tmp2"`
+    logger --id=$$ -p user.error -t bogofilter "Error marking message $mid as {{ item }}: exited with status $ret, output: $output"
     exit "$ret"
 fi
diff --git a/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier b/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier
--- a/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier
+++ b/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier
@@ -1,20 +1,25 @@
 #!/bin/bash
 
 export PATH=/usr/sbin:/usr/bin:/sbin:/bin
-logger -p user.info -t bogofilter "Classifying message as either spam or ham."
 tmp=`mktemp`
 trap "rm -f $tmp" EXIT
 ret=0
-output=$(cat > "$tmp" 2>&1) || ret=$?
+cat > "$tmp" || ret=$?
 if [ "$ret" != "0" ] ; then
-    logger -p user.error -t bogofilter "Error buffering incoming message: exited with status $ret, output: $output"
+    logger -p user.error -t bogofilter "Error buffering incoming message: exited with status $ret"
+    exit "$ret"
 fi
+
+mid=$(grep ^Message-ID: < "$tmp" | head -1 | cut -d '<' -f 2 | cut -d '>' -f 1)
+if [ "$mid" == "" ] ; then mid="with no discernible ID" ; fi
+logger --id=$$ -p user.info -t bogofilter "Classifying message $mid as either spam or ham."
+
 tmp2=`mktemp`
 trap "rm -f $tmp $tmp2" EXIT
 bogofilter -p -e {% if spam.autoregister_incoming_mail|default(False) %}-u {% endif %}-l -C -I "$tmp" 2> "$tmp2"
 ret=$?
 if [ "$ret" != "0" ] ; then
     output=`cat "$tmp2"`
-    logger -p user.error -t bogofilter "Error classifying message: exited with status $ret, output: $output"
+    logger --id=$$ -p user.error -t bogofilter "Error classifying message $mid: exited with status $ret, output: $output"
     exit "$ret"
 fi
