Fix various bugs in the classifier, and make it more robust.

diff --git a/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier b/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier
--- a/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier
+++ b/roles/mailserver/templates/dovecot/usr/local/libexec/sieve/spamclassifier
@@ -3,6 +3,12 @@
 export PATH=/usr/sbin:/usr/bin:/sbin:/bin
 logger -p user.info -t bogofilter "Classifying message as either spam or ham."
 tmp=`mktemp`
+trap "rm -f $tmp" EXIT
+ret=0
+output=$(cat > "$tmp" 2>&1) || ret=$?
+if [ "$ret" != "0" ] ; then
+    logger -p user.error -t bogofilter "Error buffering incoming message: exited with status $ret, output: $output"
+fi
 tmp2=`mktemp`
 trap "rm -f $tmp $tmp2" EXIT
 bogofilter -p -e -u -l -C -I "$tmp" 2> "$tmp2"
